version: '2'

services:
  app:
    build: '.'
    container_name: app
    depends_on:
      - db
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - DATASOURCE_USERNAME=compose-postgres
      - DATASOURCE_PASSWORD=compose-postgres
      - JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=my-super-secret
      - JWT_EXPIRATION=600000
    ports:
      - 8080:8080

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - 5432:5432